### ISSUE TITLE
IDs not matching PDB characteristics (chain number and ID, for instance)

### ISSUE THREAD

**Issue by n4ndoz** [aqlaboratory/proteinnet#23]
Hi, first of all, thank you for the huge contribution of putting ProteinNet together great contribution to the comunity indeed.

I am now trying to fetch from PDB the Beta Carbon coordinates for each protein on ProteinNet for my algorithm. The problem is that I cannot intuitively do so via Biopython since some ID's wont inform the chain used on ProteinNet.

'1IQ8_d1iq8b4',
 '1S2M_d1s2ma2',
 '1IZ6_d1iz6b2',

Those 3 proteins as an example, have "strange" descriptors in place of chain id and number.  What do they mean after all? How could I fetch the same sequence and structure as given in ProteinNet?
I am well aware of the problems regarding mmCIF files, and the mismatch of sequences. Is there any way to solve it? I really need to implement this change.

THanks

**Comment by alquraishi** [comment]
Hi, the descriptors are described on [this page](https://github.com/aqlaboratory/proteinnet/blob/master/docs/proteinnet_records.md#file-formats).

**Comment by jessevig** [comment]
I also wanted to thank you for this very useful library. I have the same question as posted above, and unfortunately I couldn't find the answer in the linked documentation, but please let me know if I'm missing something. I found that about 28,000 of the records in the Training 100 file have the unexpected format described above for the ID field, e.g. '1IQ8_d1iq8b4', and the remainder are of the expected format, e.g. '1Z5O_1_A'. Do you have any insight on this? Many thanks in advance.

**Comment by alquraishi** [comment]
Hi @jessevig, thanks for pointing this out. I had missed what the issue was. You're right, there's a second type of identifier, relating to entries from [ASTRAL](http://scop.berkeley.edu/astral/ver=2.07) and not the PDB, which is a database of individual protein domains as opposed to full-length proteins. I found that combining both is helpful in training models. In your example, "1IQ8" is the PDB id of the original chain from which the ASTRAL domain is derived, and "d1iq8b4" is the ASTRAL id.

**Comment by jessevig** [comment]
Got it, thanks for the explanation!
