### ISSUE TITLE
Unequal sequence length in MSA

### ISSUE THREAD

**Issue by chris-clem** [aqlaboratory/proteinnet#9]
Hi,

I was wondering why some MSAs, e.g. 102L_1_A consist of sequences of unequal length. 
If I run the following code:
```python
from Bio import SeqIO

for index, record in enumerate(SeqIO.parse("ProteinNet/raw/102L_1_A.a2m", "fasta")):
    if index > 4: break
    print("index %i, ID = %s, length %i"
          % (index, record.id, len(record.seq)))
```
I get the following output:
```
index 0, ID = XXXX_UPI00066315A6/35-154, length 165
index 1, ID = XXXX_UPI00066315A6/175-292, length 165
index 2, ID = TB_PC08_66DRAFT_100509362|3300000228|metagenome/9-106, length 165
index 3, ID = TB_PC08_66DRAFT_100509362|3300000228|metagenome/113-206, length 165
index 4, ID = JGI25909J50240_10726711|3300003393|metagenome/24-165, length 166
```
Index 4 has length 166, the others 165. 
Can I pad the shorter sequences with '-' in the end?

Best
Christoph

**Comment by alquraishi** [comment]
The unequal length is due to an insertion in the fifth sequence (insertions are denoted by lowercase letters). The first sequence is the reference to which all other sequences are aligned. Dashes indicate gaps and lowercase letters insertions. I would not pad with `-`. If you want to get a standard alignment simply remove all lowercase letters.

**Comment by chris-clem** [comment]
Thanks for the clarification!
